name: lms_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  dashed_circular_progress_bar: ^0.0.6
  remixicon: ^1.4.1
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Urbanist/
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/Urbanist/Urbanist-Regular.ttf
        - asset: assets/Urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/Urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/Urbanist/Urbanist-Light.ttf
          weight: 300
